modLoader="javafml"
loaderVersion="[35,)"
license="GNU General Public License 3"

issueTrackerURL="https://github.com/DancZer/Excavator/issues" #optional

[[mods]]
modId="excavator"
version="${file.jarVersion}"
displayName="Excavator"
updateJSONURL="http://myurl.me/"
displayURL="https://github.com/DancZer/Excavator/wiki"
logoFile="excavator.png"
credits=""
authors="Created by Laszlo Tanczos."
description="Add a simple excavator to help your mining."

[[dependencies.excavator]]
    modId="forge"
    mandatory=true
    versionRange="[35,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.excavator]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.4,1.17)"
    ordering="NONE"
    side="BOTH"
